### ISSUE TITLE
Program should handle uppercase and lowercase

### ISSUE THREAD

**Issue by martinlindf** [svj0hn/wasp-piglatin#10]
If a word is written in uppercase, the output should be written in uppercase, and similarly in lowercase.

**Comment by svj0hn** [comment]
Also, if only the first letter in the original word is uppercase, the same should probably go for the result.

How would we handle stuff like "upPErcase" or "LOWercase" though? Keep same word format or actually transfer letters to the end?

**Comment by martinlindf** [comment]
I will make an arbitrary decision and stick to it. :-)

I'll take this one though.

**Comment by martinlindf** [comment]
This has been solved. https://github.com/svj0hn/wasp-piglatin/pull/34
