### ISSUE TITLE
Handling of non-letter inputs

### ISSUE THREAD

**Issue by martinlindf** [svj0hn/wasp-piglatin#11]
Non-letter inputs in the string should be handled as spaces, ignoring them.

**Comment by svj0hn** [comment]
Should they also be considered spaces for word separation purposes?

**Comment by martinlindf** [comment]
Not sure. Should we handle arbitrary characters in arbitrary sequences?

**Comment by svj0hn** [comment]
Technically, I guess the concept of "Pig Latin" doesn't really apply to non-letters.

With that in mind, we could:
 - Ignore non-letters, just removing them from the word before translation
 - Ignore words containing non-letters completely
 - Just give an error, informing the user of the error of their ways

Either way, spaces, commas and semicolons could be valid separators once multi-word functionality is introduced.

**Comment by svj0hn** [comment]
A couple of open cases we may want to decide how to handle:

Non-letter characters without spaces:
"foo,bar" -> "oofay,arbay" // "oo,barfay" // "oofay arbay" // "oofay, arbay"

In between words: 
"hello, you imbecile" -> "ellohay, youway imbecileway" // "ellohay youway imbecileway"

Sentence termination:
"hello world!" -> "ellohay orldway!" // "ellohay orld!way" // "ellohay orldway"

**Comment by martinlindf** [comment]
Issue is basically solved. Merging in.
