### ISSUE TITLE
Reverse translation

### ISSUE THREAD

**Issue by martinlindf** [svj0hn/wasp-piglatin#12]
It should be possible to translate pig latin words back to english

**Comment by svj0hn** [comment]
Any ideas on how the program should determine if a word started with "w", which was moved to the end, then appended with "ay", or if it started with a vowel and "way" was added to the end?

**Comment by martinlindf** [comment]
awayway -> away | waway

No idea, seems hard. Think we will just have to default to one. If we really want to tryhard, we can make dictionary checks. But that I don't want to do.

**Comment by svj0hn** [comment]
Me neither... There doesn't seem to be any way (:>) to tell the difference without knowing the possible original words.

**Comment by antekillen** [comment]
I will start this one!  Plan is to output all options... Ok?

**Comment by antekillen** [comment]
Adressed in last commit!
